dist: xenial
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
deploy:
  provider: pypi
  user: amcpherson
  password:
    secure: XGQ5I0JMdk++M+uUnYa76HjOfOw1GXgIpVQz6RzIDSNS+GtdxA371uNh43rpwrxOPsMxCb5ckoRCWAzNBUIu6mLslpmdoNesgO7P46ZxAhZjhlRpXIULBvCazc2asN3O7nH5qcAYpLS1cKXyTD/BBoamoafC1IsFGHKspxi2es0w9gcWyA/+jyoPVs0bYcYyyuZi0vE33l8LYFDrdH1lwpDE8s00SNpDb/IzPy4MO7E4Zcq/EhQJxQ6XE+KUv8d7f6RmnAEUoe4uj46SnLfS4a9qdtw4L7hZL6hN8PMZkXzw1DXTOgKGa1wqOvwHxcO++BrYhlXkaEjUG9DDBx/EKxLvg5frCLrvVg4adg6I2TyZr06Ge2I/W6nKqdBwxM4qV0vluzlejuefB4x4WWl03ZuVII37HSM/R0bVCMicaa+BbszPUvwhxw08kRH7dy1JPR/lq+hTPvrxsEyLvjJvHc1wk1ZjNpqvsPwqV4EYSQ8xxyOJNMt8opHfNQnM6E/JUdAQ2bS+ID40gel2jUnJUk3R/IiZeXu7qBLQJlPobfcfBTSHT2XrNkHl/AUhEm9MtqrlZGDBVDcnf/PDLAHSp+VnR5fZccp/dXWZRcPjCGFgnBUOYZPO2+yKfpkxvOvFvLinh/R2mCYqnwH57p6p+ONn8Y1Da1XgG1knDHaNp7Q=
  on:
    tags: true
script:
- echo "skipping tests"
install: true
